name: devops-experiment-tensorflow-machinelearning
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ubuntu:20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies and train model
        run: |
          apt-get update && apt-get install -y python3 python3-pip
          pip install -r requirements.txt
          python model.py

         
